"""add_product_image_path

Revision ID: 2bc4531c97bb
Revises: b6bfb6147316
Create Date: 2026-05-06 19:05:36.444101
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2bc4531c97bb"
down_revision = 'b6bfb6147316'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_path', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_path')
    # ### end Alembic commands ###
