"""add_captures

Revision ID: 2e23603f5f4d
Revises: 862bfe1a34b8
Create Date: 2026-05-05 15:34:48.478724
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e23603f5f4d"
down_revision = '862bfe1a34b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captures_id'), 'captures', ['id'], unique=False)
    op.create_index(op.f('ix_captures_sku'), 'captures', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captures_sku'), table_name='captures')
    op.drop_index(op.f('ix_captures_id'), table_name='captures')
    op.drop_table('captures')
    # ### end Alembic commands ###
