"""add_product_location_fields

Revision ID: 7f2c92ffd1e0
Revises: 2e23603f5f4d
Create Date: 2026-05-06 17:52:51.010533
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f2c92ffd1e0"
down_revision = '2e23603f5f4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('aisle', sa.String(length=32), nullable=True))
    op.add_column('products', sa.Column('shelf', sa.String(length=32), nullable=True))
    op.add_column('products', sa.Column('shelf_level', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'shelf_level')
    op.drop_column('products', 'shelf')
    op.drop_column('products', 'aisle')
    # ### end Alembic commands ###
