"""remove_gender

Revision ID: b6bfb6147316
Revises: 7f2c92ffd1e0
Create Date: 2026-05-06 18:59:09.957432
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6bfb6147316"
down_revision = '7f2c92ffd1e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('gender', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
